[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pdf_chat_api"
version = "0.1.0"
authors = [
    { name = "Huzeyfe", email = "huzeyfebicakci@gmail.com" },
]
description = "A PDF Chat API using FastAPI and Gemini"
requires-python = ">=3.8"